SEED: 7
DEBUG: False
CHECKPOINT: 20
SAVE_CHECKPOINTS: [20]
OUTPUT_BASE_DIR: '/storage/shafner/burn_severity_mapping/networks/'

MODEL:
  TYPE: 'unet'
  TOPOLOGY: [64, 128,]
  OUT_CHANNELS: 4
  IN_CHANNELS: 10
  LOSS_TYPE: 'CrossEntropyLoss'

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True

DATASET:
  PATH: '/storage/shafner/burn_severity_mapping/wildfire_dataset'
  LABEL: 'burnseverity'
  USE_FIREMASK: True
  THRESHOLDS: []
  CLASSES: ['unburnt', 'low', 'moderate', 'high']
  MODE: 'optical'
  AVAILABLE_S2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
  S2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
  S2_PROCESSING_LEVEL: 'toa'
  AVAILABLE_S1_BANDS: ['kCR', 'kVH', 'kVV']
  S1_BANDS: ['kCR', 'kVH', 'kVV']

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 8
  OPTIMIZER: 'adamw'
  WEIGHT_DECAY: 1e-2
  EPOCHS: 20
  LR_DECAY_FACTOR: 1
  LR_DECAY_INTERVAL: 1e10

AUGMENTATION:
  OVERSAMPLING: False
  CROP_TYPE: 'none' # uniform or importance
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR: False
  GAMMA: False