_BASE_: "base.yaml"
DEBUG: False
CHECKPOINT: 10

MODEL:
  OUT_CHANNELS: 3
  LOSS_TYPE: 'CrossEntropyLoss'

DATASET:
  LABEL: 'dnbr'
  THRESHOLDS: [0.15, 0.65]
  CLASSES: ['no', 'low', 'high']
  MODE: 'optical'