_BASE_: "base.yaml"
DEBUG: False
CHECKPOINT: 20

MODEL:
  IN_CHANNELS: 3

DATASET:
  PATH: '/storage/shafner/burn_severity_mapping/wildfire_dataset'
  LABEL: 'dnbr'
  SITES: ['elephanthill']
  USE_FIREMASK: True
  THRESHOLDS: [50, 350, 650]
  CLASSES: ['unburnt', 'low', 'moderate', 'high']
  MODE: 'sar'
  AVAILABLE_S1_BANDS: ['kCR', 'kVH', 'kVV']
  S1_BANDS: ['kCR', 'kVH', 'kVV']