_BASE_: "base.yaml"
DEBUG: False
CHECKPOINT: 20

MODEL:
  IN_CHANNELS: 20

DATASET:
  PATH: '/storage/shafner/burn_severity_mapping/wildfire_dataset'
  LABEL: 'rbr'
  USE_FIREMASK: False
  THRESHOLDS: [0.05, 0.35, 0.55]
  CLASSES: ['unburnt', 'low', 'moderate', 'high']
  MODE: 'optical'
  AVAILABLE_S2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
  S2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
  S2_PROCESSING_LEVEL: 'toa'
  INCLUDE_PREFIRE_S2: True